export const ROUTES = {
  LOGIN: "/login",
  DASHBOARD: "/",
  ORDERS: "/orders",
  ORDER_DETAIL: "/orders/:id",
  PRODUCTS: "/products",
  PRODUCT_DETAIL: "/products/:id",
  PRODUCT_CREATE: "/products/new",
  PRODUCT_EDIT: "/products/:id/edit",
  USERS: "/users",
  USER_DETAIL: "/users/:id",
  WALLETS: "/wallets",
  WALLET_DETAIL: "/wallets/:id",
  WITHDRAWALS: "/withdrawals",
  WITHDRAWAL_DETAIL: "/withdrawals/:id",
  REFUNDS: "/refunds",
  REFUND_DETAIL: "/refunds/:id",
} as const;
